// packages/vue-img-mapper/src/ImageMapper.vue
<script setup lang="ts">
import type { ImageMapperListeners, ImageMapperProps, MapArea, Refs } from '@/@types';
import { CTX } from '@/@types/draw';
import { generateProps } from '@/helpers/constants';
import styles from '@/helpers/styles';

import { computed, getCurrentInstance, onMounted, onUnmounted, ref, watch } from 'vue';

const emit = defineEmits<ImageMapperListeners>();
const props = defineProps<ImageMapperProps>();
const {
  src,
  name,
  areas,
  areaKeyName,
  isMulti,
  toggle,
  active,
  disabled,
  fillColor,
  strokeColor,
  lineWidth,
  imgWidth,
  width,
  height,
  natural,
  responsive,
  parentWidth,
  containerProps,
  imgProps,
  canvasProps,
  mapProps,
  areaProps,
} = generateProps(props);

const instance = getCurrentInstance();
const hasClickListener = computed(() => !!instance?.vnode?.props?.onClick);

const isRendered = ref<boolean>(false);
const areasRef = ref<MapArea[]>(areas);
const containerRef = ref<Refs['containerRef']>(null);
const img = ref<Refs['imgRef']>(null);
const canvasRef = ref<Refs['canvasRef']>(null);
const ctx = ref<CTX<null>['value']>(null);
const interval = ref<number>(0);
// const prevState = 0;

const init = () => {
  if (img.value?.complete && canvasRef.value && containerRef.value) {
    ctx.value = canvasRef.value.getContext('2d');

    isRendered.value = true;
  }
};

watch(isRendered, (newVal) => {
  if (newVal && interval.value) {
    clearInterval(interval.value);
  }
});

onMounted(() => {
  interval.value = window.setInterval(init, 500);
});

// const filteredAreas = computed(() => props.areas.filter(area => !area.disabled));

// // Helper functions
// const getDimensions = () => {
//   if (!img.value) return { width: 0, height: 0 };

//   if (props.natural) {
//     return {
//       width: img.value.naturalWidth,
//       height: img.value.naturalHeight,
//     };
//   }

//   if (props.width && props.height) {
//     return {
//       width: typeof props.width === 'number' ? props.width : img.value.clientWidth,
//       height: typeof props.height === 'number' ? props.height : img.value.clientHeight,
//     };
//   }

//   if (props.responsive && props.parentWidth) {
//     const ratio = img.value.naturalHeight / img.value.naturalWidth;
//     return {
//       width: props.parentWidth,
//       height: props.parentWidth * ratio,
//     };
//   }

//   return {
//     width: img.value.clientWidth || img.value.naturalWidth,
//     height: img.value.clientHeight || img.value.naturalHeight,
//   };
// };

// const getExtendedArea = (area: MapArea) => {
//   const dimensions = getDimensions();
//   const imgWidth = props.imgWidth || img.value?.naturalWidth || dimensions.width;

//   const scaleX = dimensions.width / imgWidth;
//   const scaleY = dimensions.height / (img.value?.naturalHeight || dimensions.height);

//   const scaledCoords = area.coords.map((coord: number, i: number) =>
//     i % 2 === 0 ? coord * scaleX : coord * scaleY
//   );

//   return {
//     ...area,
//     scaledCoords,
//     fillColor: area.fillColor || props.fillColor,
//     strokeColor: area.strokeColor || props.strokeColor,
//     lineWidth: area.lineWidth || props.lineWidth,
//     active: area.active !== undefined ? area.active : props.active,
//   };
// };

// const getScaledCoords = (area: MapArea) => {
//   return getExtendedArea(area).scaledCoords;
// };

// const drawShape = (area: any) => {
//   if (!ctx.value) return false;

//   const { scaledCoords, shape, fillColor, strokeColor, lineWidth } = area;

//   ctx.value.beginPath();

//   if (shape === 'circle') {
//     const [x, y, radius] = scaledCoords;
//     ctx.value.arc(x, y, radius, 0, 2 * Math.PI);
//   } else if (shape === 'rect') {
//     const [x, y, width, height] = scaledCoords;
//     ctx.value.rect(x, y, width, height);
//   } else if (shape === 'poly') {
//     ctx.value.moveTo(scaledCoords[0], scaledCoords[1]);
//     for (let i = 2; i < scaledCoords.length; i += 2) {
//       ctx.value.lineTo(scaledCoords[i], scaledCoords[i + 1]);
//     }
//     ctx.value.closePath();
//   }

//   if (fillColor) {
//     ctx.value.fillStyle = fillColor;
//     ctx.value.fill();
//   }

//   if (strokeColor) {
//     ctx.value.strokeStyle = strokeColor;
//     ctx.value.lineWidth = lineWidth || 1;
//     ctx.value.stroke();
//   }

//   return true;
// };

// const clearCanvas = () => {
//   if (!ctx.value || !canvasRef.value) return;
//   ctx.value.clearRect(0, 0, canvasRef.value.width, canvasRef.value.height);
// };

// const renderPrefilledAreas = () => {
//   props.areas.forEach(area => {
//     const extendedArea = getExtendedArea(area);
//     if (extendedArea.preFillColor) {
//       drawShape({ ...extendedArea, fillColor: extendedArea.preFillColor });
//     }
//   });
// };

// const resetCanvasAndPrefillArea = () => {
//   clearCanvas();
//   renderPrefilledAreas();
// };

// const highlightArea = (area: MapArea) => {
//   const extendedArea = getExtendedArea(area);
//   if (!extendedArea.active) return false;
//   return drawShape(extendedArea);
// };

// const onHighlightArea = (area: MapArea) => {
//   const chosenArea = props.isMulti
//     ? area
//     : areasRef.value.find(c => c[props.areaKeyName] === area[props.areaKeyName]);

//   if (!chosenArea) return;

//   const extendedArea = getExtendedArea(chosenArea);
//   if (!(props.active && extendedArea.active)) return;

//   const newArea = { ...chosenArea };

//   const isCurrentAreaSelected = props.toggle &&
//     (props.isMulti ? newArea.preFillColor : !!area.preFillColor);

//   if (isCurrentAreaSelected) {
//     const isPreFillColorFromJSON = props.areas.find(
//       c => c[props.areaKeyName] === area[props.areaKeyName]
//     );
//     if (isPreFillColorFromJSON?.preFillColor) {
//       delete newArea.preFillColor;
//     }
//   } else {
//     newArea.preFillColor = extendedArea.fillColor;
//   }

//   const chosenAreas = props.isMulti ? props.areas : areasRef.value;
//   const updatedAreas = chosenAreas.map(cur =>
//     cur[props.areaKeyName] === area[props.areaKeyName] ? newArea : cur
//   );

//   if (props.onChange) {
//     props.onChange(newArea, updatedAreas);
//   }

//   areasRef.value = updatedAreas;
// };

// const initCanvas = (isFirstTime = true, triggerOnLoad = false) => {
//   const dimensions = getDimensions();

//   if (!img.value || !canvasRef.value || !containerRef.value || !ctx.value) return;

//   containerRef.value.style.width = `${dimensions.width}px`;
//   containerRef.value.style.height = `${dimensions.height}px`;

//   if (isFirstTime) {
//     nextTick(() => initCanvas(false, true));
//   } else {
//     img.value.width = dimensions.width;
//     img.value.height = dimensions.height;

//     canvasRef.value.width = dimensions.width;
//     canvasRef.value.height = dimensions.height;

//     renderPrefilledAreas();
//   }

//   if (props.onLoad && triggerOnLoad && img.value) {
//     props.onLoad(img.value, dimensions);
//   }
// };

// // Event handlers
// const handleImageClick = (e: MouseEvent) => {
//   if (props.onImageClick) props.onImageClick(e);
// };

// const handleImageMouseMove = (e: MouseEvent) => {
//   if (props.onImageMouseMove) props.onImageMouseMove(e);
// };

// const handleAreaClick = (area: MapArea, index: number, e: MouseEvent) => {
//   if (props.onClick) props.onClick(area, index, e);
//   onHighlightArea(area);
// };

// const handleAreaMouseDown = (area: MapArea, index: number, e: MouseEvent) => {
//   if (props.onMouseDown) props.onMouseDown(area, index, e);
// };

// const handleAreaMouseEnter = (area: MapArea, index: number, e: MouseEvent) => {
//   if (props.onMouseEnter) props.onMouseEnter(area, index, e);
//   if (props.active) highlightArea(area);
// };

// const handleAreaMouseLeave = (area: MapArea, index: number, e: MouseEvent) => {
//   if (props.onMouseLeave) props.onMouseLeave(area, index, e);
//   if (props.active) resetCanvasAndPrefillArea();
// };

// const handleAreaMouseMove = (area: MapArea, index: number, e: MouseEvent) => {
//   if (props.onMouseMove) props.onMouseMove(area, index, e);
// };

// const handleAreaMouseUp = (area: MapArea, index: number, e: MouseEvent) => {
//   if (props.onMouseUp) props.onMouseUp(area, index, e);
// };

// const handleAreaTouchStart = (area: MapArea, index: number, e: TouchEvent) => {
//   if (props.onTouchStart) props.onTouchStart(area, index, e);
// };

// const handleAreaTouchEnd = (area: MapArea, index: number, e: TouchEvent) => {
//   if (props.onTouchEnd) props.onTouchEnd(area, index, e);
// };

// const getAreaProps = (area: MapArea, index: number) => {
//   if (Array.isArray(props.areaProps)) {
//     if (props.areaKeyName) {
//       return props.areaProps.find(
//         cur => cur && cur[props.areaKeyName] === area[props.areaKeyName]
//       );
//     }
//     return props.areaProps[index];
//   }
//   return props.areaProps;
// };

// const getAreaClasses = (area: MapArea, index: number) => {
//   const classes = ['img-mapper-area'];
//   if (area.preFillColor) classes.push('img-mapper-area-highlighted');
//   const areaProps = getAreaProps(area, index);
//   if (areaProps?.className) classes.push(areaProps.className);
//   return classes.join(' ');
// };

// // Watchers
// watch(() => props.areas, () => {
//   areasRef.value = [...props.areas];
//   resetCanvasAndPrefillArea();
// }, { deep: true });

// watch([() => props.width, () => props.height, () => props.parentWidth], () => {
//   if (isRendered.value) {
//     initCanvas();
//   }
// });

// // Lifecycle
// onMounted(() => {
//   interval.value = window.setInterval(init, 500);
// });

// onUnmounted(() => {
//   if (interval.value) {
//     clearInterval(interval.value);
//   }
// });

defineExpose({
  getRefs: () => ({
    containerRef: containerRef.value,
    img: img.value,
    canvasRef: canvasRef.value,
  }),
});

onUnmounted(() => {
  if (interval.value) {
    clearInterval(interval.value);
  }
});
</script>

<template>
  <div
    v-bind="containerProps"
    ref="containerRef"
    id="img-mapper"
    :style="[containerProps?.style, styles.container]"
  >
    <img
      alt="map"
      role="presentation"
      v-bind="imgProps"
      ref="img"
      @click="handleImageClick"
      @mousemove="handleImageMouseMove"
      :src="src"
      :useMap="`#${name}`"
      class="img-mapper-img"
      :style="[styles.img(responsive), isRendered ? null : { display: 'none' }]"
    />
    <canvas v-bind="canvasProps" ref="canvasRef" class="img-mapper-canvas" :style="styles.canvas" />
    <map
      v-bind="mapProps"
      :name="name"
      class="img-mapper-map"
      :style="styles.map(!!hasClickListener)"
    >
      <!-- <template v-if="isRendered && !disabled">
        <area
          v-for="(area, index) in filteredAreas"
          :key="area[areaKeyName] ?? index.toString()"
          alt="map"
          v-bind="getAreaProps(area, index)"
          :coords="getScaledCoords(area).join(',')"
          :href="area.href ?? getAreaProps(area, index)?.href"
          :shape="area.shape ?? getAreaProps(area, index)?.shape"
          :class="getAreaClasses(area, index)"
          @click="handleAreaClick(area, index, $event)"
          @mousedown="handleAreaMouseDown(area, index, $event)"
          @mouseenter="handleAreaMouseEnter(area, index, $event)"
          @mouseleave="handleAreaMouseLeave(area, index, $event)"
          @mousemove="handleAreaMouseMove(area, index, $event)"
          @mouseup="handleAreaMouseUp(area, index, $event)"
          @touchstart="handleAreaTouchStart(area, index, $event)"
          @touchend="handleAreaTouchEnd(area, index, $event)"
        />
      </template> -->
    </map>
  </div>
</template>

// packages/react-img-mapper/src/ImageMapper.tsx
import React, {
  memo,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react';

import isEqual from 'react-fast-compare';

import { getExtendedArea } from '@/helpers/area';
import { generateProps, rerenderPropsList } from '@/helpers/constants';
import { getDimension, getDimensions, getPropDimension } from '@/helpers/dimensions';
import drawShape from '@/helpers/draw';
import {
  click,
  imageClick,
  imageMouseMove,
  mouseDown,
  mouseEnter,
  mouseLeave,
  mouseMove,
  mouseUp,
  touchEnd,
  touchStart,
} from '@/helpers/events';
import styles from '@/helpers/styles';

import type { FC, ReactNode } from 'react';

import type { ImageMapperPropsWithRef, MapArea, Refs } from '@/@types';
import type { PrevStateRef } from '@/@types/dimensions';
import type { CTX } from '@/@types/draw';

export type * from '@/@types';

const ImageMapper: FC<ImageMapperPropsWithRef> = ({ ref, ...props }) => {
  const generatedProps = generateProps(props);
  const {
    src,
    name,
    areas,
    areaKeyName,
    isMulti,
    toggle,
    active,
    disabled,
    fillColor,
    strokeColor,
    lineWidth,
    imgWidth,
    width,
    height,
    natural,
    responsive,
    parentWidth,
    containerProps,
    imgProps,
    canvasProps,
    mapProps,
    areaProps,

    onChange,
    onImageClick,
    onImageMouseMove,
    onClick,
    onMouseDown,
    onMouseUp,
    onTouchStart,
    onTouchEnd,
    onMouseMove,
    onMouseEnter,
    onMouseLeave,
    onLoad,
  } = generatedProps;

  const [isRendered, setIsRendered] = useState<boolean>(false);
  const areasRef = useRef<MapArea[]>(areas);
  const containerRef = useRef<Refs['containerRef']>(null);
  const img = useRef<Refs['imgRef']>(null);
  const canvas = useRef<Refs['canvasRef']>(null);
  const ctx = useRef<CTX<null>['current']>(null);
  const interval = useRef<number>(0);
  const prevState = useRef<PrevStateRef>({
    parentWidth,
    ...getPropDimension({ width, height, img }),
  });

  const dimensionParams = useMemo(
    () => ({ width, height, responsive, parentWidth, natural }),
    [width, height, responsive, parentWidth, natural],
  );

  const scaleCoordsParams = useMemo(
    () => ({ width, height, responsive, parentWidth, imgWidth }),
    [width, height, responsive, parentWidth, imgWidth],
  );

  const areaParams = useMemo(
    () => ({ fillColor, lineWidth, strokeColor }),
    [fillColor, lineWidth, strokeColor],
  );

  const init = useCallback(() => {
    if (img.current?.complete && canvas.current && containerRef.current) {
      ctx.current = canvas.current.getContext('2d');

      setIsRendered(true);
    }
  }, []);

  useEffect(() => {
    if (isRendered) {
      clearInterval(interval.current);
    } else {
      // eslint-disable-next-line unicorn/prefer-global-this
      interval.current = window.setInterval(init, 500);
    }
  }, [init, isRendered]);

  const renderPrefilledAreas = useCallback(() => {
    // eslint-disable-next-line unicorn/no-array-for-each
    areas.forEach((area) => {
      const extendedArea = getExtendedArea(area, { img, ...scaleCoordsParams }, areaParams);

      if (!extendedArea.preFillColor) return false;

      return drawShape({ ...extendedArea, fillColor: extendedArea.preFillColor }, ctx);
    });
  }, [areaParams, areas, scaleCoordsParams]);

  const clearCanvas = useCallback(() => {
    if (!(ctx.current && canvas.current)) return;

    ctx.current.clearRect(0, 0, canvas.current.width, canvas.current.height);
  }, []);

  const resetCanvasAndPrefillArea = useCallback(() => {
    clearCanvas();
    renderPrefilledAreas();
  }, [clearCanvas, renderPrefilledAreas]);

  const highlightArea = (area: MapArea): boolean => {
    const extendedArea = getExtendedArea(area, { img, ...scaleCoordsParams }, areaParams);

    if (!extendedArea.active) return false;

    return drawShape(extendedArea, ctx);
  };

  const onHighlightArea = (area: MapArea): void => {
    const chosenAreasRef = areasRef.current;

    const chosenArea = isMulti
      ? area
      : chosenAreasRef.find((c) => c[areaKeyName] === area[areaKeyName]);

    if (!chosenArea) return;

    const extendedArea = getExtendedArea(chosenArea, { img, ...scaleCoordsParams }, areaParams);
    if (!(active && extendedArea.active)) return;

    const chosenAreas = isMulti ? areas : chosenAreasRef;
    const newArea = { ...chosenArea };

    const isCurrentAreaSelected = (() => {
      if (toggle) {
        if (isMulti && newArea.preFillColor) return true;
        return !isMulti && !!area.preFillColor;
      }

      return false;
    })();

    if (isCurrentAreaSelected) {
      const isPreFillColorFromJSON = chosenAreas.find((c) => c[areaKeyName] === area[areaKeyName]);
      if (isPreFillColorFromJSON?.preFillColor) delete newArea.preFillColor;
    } else {
      newArea.preFillColor = extendedArea.fillColor;
    }

    const updatedAreas = chosenAreas.map((cur) =>
      cur[areaKeyName] === area[areaKeyName] ? newArea : cur,
    );

    if (onChange) onChange(newArea, updatedAreas);
  };

  const initCanvas = useCallback(
    (isFirstTime = true, triggerOnLoad = false) => {
      const { width: imageWidth, height: imageHeight } = getDimensions({ img, ...dimensionParams });

      if (!(img.current && canvas.current && containerRef.current && ctx.current)) return;

      containerRef.current.style.width = `${imageWidth}px`;
      containerRef.current.style.height = `${imageHeight}px`;

      if (isFirstTime) {
        initCanvas(false, true);
      } else {
        img.current.width = imageWidth;
        img.current.height = imageHeight;

        canvas.current.width = imageWidth;
        canvas.current.height = imageHeight;

        renderPrefilledAreas();
      }

      if (onLoad && triggerOnLoad) {
        onLoad(img.current, { width: imageWidth, height: imageHeight });
      }
    },
    [dimensionParams, onLoad, renderPrefilledAreas],
  );

  const getRefs = useCallback(
    () => ({ containerRef: containerRef.current, imgRef: img.current, canvasRef: canvas.current }),
    [],
  );

  useEffect(() => {
    if (isRendered) initCanvas();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isRendered]);

  useEffect(() => {
    resetCanvasAndPrefillArea();
  }, [areas, resetCanvasAndPrefillArea]);

  useEffect(() => {
    if (responsive && parentWidth && prevState.current.parentWidth !== parentWidth) {
      initCanvas();
      prevState.current.parentWidth = parentWidth;
    }

    if (width && prevState.current.width !== width) {
      initCanvas();
      prevState.current.width = getDimension(width, img);
    }

    if (height && prevState.current.height !== height) {
      initCanvas();
      prevState.current.height = getDimension(height, img);
    }
  }, [height, initCanvas, parentWidth, responsive, width]);

  useImperativeHandle(ref, () => ({ getRefs }), [getRefs]);

  const handleMouseEnter = (area: MapArea): void => {
    if (active) highlightArea(area);
  };

  const handleMouseLeave = (): void => {
    if (active) resetCanvasAndPrefillArea();
  };

  const handleClick = (area: MapArea): void => {
    onHighlightArea(area);
  };

  const renderAreas = (): ReactNode =>
    areas.map((area, index) => {
      const { areaKeyName: areaKeyNameProp } = props;

      const { scaledCoords } = getExtendedArea(area, { img, ...scaleCoordsParams }, areaParams);

      if (area.disabled) return null;

      const { preFillColor, shape, href } = area;
      const currentAreaProps = (() => {
        if (Array.isArray(areaProps)) {
          if (areaKeyNameProp) {
            return areaProps.find((cur) => cur && cur[areaKeyNameProp] === area[areaKeyNameProp]);
          }

          return areaProps[index];
        }

        return areaProps;
      })();

      return (
        <area
          alt="map"
          {...currentAreaProps}
          key={area[areaKeyName] ?? index.toString()}
          coords={scaledCoords.join(',')}
          href={href ?? currentAreaProps?.href}
          onClick={click({ area, index }, { onClick, cb: handleClick })}
          onMouseDown={mouseDown({ area, index }, { onMouseDown })}
          onMouseEnter={mouseEnter({ area, index }, { onMouseEnter, cb: handleMouseEnter })}
          onMouseLeave={mouseLeave({ area, index }, { onMouseLeave, cb: handleMouseLeave })}
          onMouseMove={mouseMove({ area, index }, { onMouseMove })}
          onMouseUp={mouseUp({ area, index }, { onMouseUp })}
          onTouchEnd={touchEnd({ area, index }, { onTouchEnd })}
          onTouchStart={touchStart({ area, index }, { onTouchStart })}
          shape={shape ?? currentAreaProps?.shape}
          className={[
            'img-mapper-area',
            ...(preFillColor ? ['img-mapper-area-highlighted'] : []),
            ...(currentAreaProps?.className ? [currentAreaProps.className] : []),
          ].join(' ')}
        />
      );
    });

  return (
    <div
      {...containerProps}
      ref={containerRef}
      id="img-mapper"
      style={{ ...containerProps?.style, ...styles.container }}
    >
      <img
        alt="map"
        role="presentation"
        {...imgProps}
        ref={img}
        onClick={imageClick({ onImageClick })}
        onMouseMove={imageMouseMove({ onImageMouseMove })}
        src={src}
        useMap={`#${name}`}
        className={['img-mapper-img', ...(imgProps?.className ? [imgProps.className] : [])].join(
          ' ',
        )}
        style={{
          ...imgProps?.style,
          ...styles.img(responsive),
          ...(isRendered ? null : { display: 'none' }),
        }}
      />
      <canvas
        {...canvasProps}
        ref={canvas}
        style={{ ...canvasProps?.style, ...styles.canvas }}
        className={[
          'img-mapper-canvas',
          ...(canvasProps?.className ? [canvasProps.className] : []),
        ].join(' ')}
      />
      <map
        {...mapProps}
        name={name}
        style={{ ...mapProps?.style, ...styles.map(!!onClick) }}
        className={['img-mapper-map', ...(mapProps?.className ? [mapProps.className] : [])].join(
          ' ',
        )}
      >
        {isRendered && !disabled ? renderAreas() : null}
      </map>
    </div>
  );
};

export default memo(ImageMapper, (prevProps, nextProps) => {
  const propChanged = rerenderPropsList.some((prop) => prevProps[prop] !== nextProps[prop]);

  return isEqual(prevProps.areas, nextProps.areas) && !propChanged;
});
